// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pklgveutwirfrbxfabnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbGd2ZXV0d2lyZnJieGZhYm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDk5NDEsImV4cCI6MjA2NzEyNTk0MX0.2MEKtu1dHa2Fcms2mpOd32y_x8tvfgc2aKho5-SPagQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});